OrdererOrgs:
    - Name: Orderer
      Domain: banking.com
      Specs:
        - Hostname: orderer
PeerOrgs:
    - Name: axisBank
      Domain: axis.com
      Template:
        Count: 3
      Users:
        Count: 0
    - Name: yesBank
      Domain: yes.com
      Template:
        Count: 3
      Users:
        Count: 0  